#!/bin/sh
case $(uname) in
	OpenBSD) sysctl | grep hw.sensors.cpu0.temp0 | sed 's/.*=//; s/\.00//; s/ deg/°/' ;;
	Linux) echo $(cat /sys/class/thermal/thermal_zone*/temp | awk '{print $1/1000}')°C ;;
esac
