#!/bin/sh
bsd() {
	sndioctl -n output.level | sed 's/0\.//' | sed 's/.$/%/' | sed 's/\.//'
}

linux() {
	wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)"%"}'
}
case $(uname) in
	*BSD) bsd ;;
	Linux) linux;;
esac
